type Country {
  id: String!
  name: String!
  users: [User!]!
}

union GetCountry = Country | InvalidIdError | NotFoundError

extend type Query {
  getAllCountries: [Country!]!
  country(id: String!): Country!
}
