interface BaseError {
  message: String!
}

type InvalidEmailError implements BaseError {
  message: String!
}

type InvalidDateError implements BaseError {
  message: String!
}

type InvalidIdError implements BaseError {
  message: String!
}

type NotFoundError implements BaseError {
  message: String!
}

type UnauthorizedError implements BaseError {
  message: String!
}