type UserMonitoring {
  id: String!
  userId: String!
  description: String!
  usage: Int!
  createdAt: String!
}

type TopUser {
  id: String!
  name: String!
  email: String!
  totalRecords: Int!
  eventType: String
}

extend type Query {
  getUserMonitoring(email: String!, startDate: String!, endDate: String!): [UserMonitoring!]!
  getTopUsersByMonitoring(startDate: String!, endDate: String!): [TopUser!]!
  getTopUsersByEventType(countryId: String!, eventType: String!, startDate: String!, endDate: String!): [User!]!
}
