type User {
  id: String!
  name: String!
  image: String!
  position: String
  email: String!
  createdAt: String!
  updatedAt: String!
  emailVerified: String
  termsAndConditionsAccepted: String
  role: Role!
  countries: [Country!]!
  userMonitoring: [UserMonitoring!]!
}

type Role {
  id: String!
  name: String!
}

extend type Query {
  getUserByEmail(email: String!): User!
  getAllUsers(pagination: Pagination): [User!]!
}
